version: "3.3"
services:
	web:
		build: .
		ports: 
			- "8080:8080"
		environment:
			ELASTICSEARCH_CLUSTER_NAME: elastic
			ELASTICSEARCH_CLUSTER_NODES: elastic:9300
		depends-on:
			- elastic
			
		elastic:
			image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
			ports:
				- "9200:9200"
				- "9300:9300"
			environment:
				node.name: elastic-0
				cluster.name: elastic
				discovery.type: "single-node"
				ES_JAVA_OPTS: "-Xms1g -Xmx1g"
				bootstrap.memory_lock: "true"
				xpack.security.enabled: "false"
				xpack.monitoring.collection.enabled: "true"
				xpack.monitoring.elasticsearch.collection.enabled: "false"
				xpack.security.transport.ssl.enabled: "false"
			unlimits:
				nproc: 65536
				nofile:
					soft: 65536
					hard: 65536
				memlock:
					soft: -1
					hard: -1							